name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    runs-on: macos-14 # Using macOS 14 (Sonoma) for latest Xcode

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build App
        run: |
          # Build for iOS
          xcodebuild clean archive \
            -scheme JitStreamer \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/JitStreamer.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      - name: Create IPA Structure
        run: |
          # Create Payload directory
          mkdir -p Payload/JitStreamer.app
          
          # Copy app contents from archive
          cp -r build/JitStreamer.xcarchive/Products/Applications/JitStreamer.app/* Payload/JitStreamer.app/
          
          # Remove code signing if present
          rm -rf Payload/JitStreamer.app/_CodeSignature
          rm -rf Payload/JitStreamer.app/embedded.mobileprovision
          
          # Create IPA
          zip -r JitStreamer-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned-ipa
          path: JitStreamer-unsigned.ipa
          retention-days: 7 