name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create IPA Structure
        run: |
          set -e
          
          echo "Creating Payload directory..."
          mkdir -p Payload/JitStreamer.app
          
          echo "Copying app contents..."
          cp -r JitStreamer/* Payload/JitStreamer.app/ || true
          
          echo "Creating Info.plist..."
          cat > Payload/JitStreamer.app/Info.plist << 'ENDOFFILE'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleIdentifier</key>
              <string>com.stik.jitstreamer</string>
              <key>CFBundleName</key>
              <string>JitStreamer</string>
              <key>CFBundleExecutable</key>
              <string>JitStreamer</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>MinimumOSVersion</key>
              <string>17.4</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>LSRequiresIPhoneOS</key>
              <true/>
          </dict>
          </plist>
          ENDOFFILE
          
          echo "Creating IPA..."
          zip -r JitStreamer.ipa Payload
          
          echo "Cleaning up..."
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned
          path: JitStreamer.ipa
          retention-days: 90 
