name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build App
        run: |
          # Build the app using your existing project
          xcodebuild clean archive \
            -project JitStreamer.xcodeproj \
            -scheme JitStreamer \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/JitStreamer.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            DEVELOPMENT_TEAM="" \
            IPHONEOS_DEPLOYMENT_TARGET=17.4

          # Show build output for debugging
          ls -la build/JitStreamer.xcarchive/Products/Applications/

      - name: Create IPA Structure
        run: |
          # Create Payload directory
          mkdir -p Payload
          
          # Copy the built .app
          cp -r build/JitStreamer.xcarchive/Products/Applications/JitStreamer.app Payload/
          
          # Show contents for debugging
          ls -la Payload/JitStreamer.app/
          
          # Create IPA
          zip -r JitStreamer.ipa Payload
          
          # Show IPA size for debugging
          ls -lh JitStreamer.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned
          path: JitStreamer.ipa
          retention-days: 90 
