name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Create IPA Structure
        run: |
          # Create basic app structure
          mkdir -p Payload/JitStreamer.app
          
          # Copy all source files and resources
          cp -r JitStreamer/* Payload/JitStreamer.app/
          
          # Create basic Info.plist
          cat > Payload/JitStreamer.app/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleIdentifier</key>
              <string>com.stik.jitstreamer</string>
              <key>CFBundleName</key>
              <string>JitStreamer</string>
              <key>CFBundleDisplayName</key>
              <string>JitStreamer</string>
              <key>CFBundleExecutable</key>
              <string>JitStreamer</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>LSRequiresIPhoneOS</key>
              <true/>
              <key>MinimumOSVersion</key>
              <string>17.4</string>
              <key>UIDeviceFamily</key>
              <array>
                  <integer>1</integer>
                  <integer>2</integer>
              </array>
              <key>UIRequiredDeviceCapabilities</key>
              <array>
                  <string>arm64</string>
              </array>
              <key>UISupportedInterfaceOrientations</key>
              <array>
                  <string>UIInterfaceOrientationPortrait</string>
                  <string>UIInterfaceOrientationLandscapeLeft</string>
                  <string>UIInterfaceOrientationLandscapeRight</string>
              </array>
              <key>UILaunchStoryboardName</key>
              <string>Launch Screen</string>
          </dict>
          </plist>
          EOF
          
          # Compile Swift files
          swiftc JitStreamer/*.swift -o Payload/JitStreamer.app/JitStreamer \
            -target arm64-apple-ios17.4 \
            -sdk $(xcrun --sdk iphoneos --show-sdk-path) \
            -F $(xcrun --sdk iphoneos --show-sdk-path)/System/Library/Frameworks \
            -framework SwiftUI \
            -framework Foundation \
            -framework UIKit \
            -framework UniformTypeIdentifiers \
            -enable-library-evolution \
            -parse-as-library \
            -whole-module-optimization \
            -emit-module \
            -module-name JitStreamer \
            -swift-version 5

          # Create IPA
          zip -r JitStreamer.ipa Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer.ipa
          path: JitStreamer.ipa
          retention-days: 90 
