name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build and Create IPA
        run: |
          # List available schemes
          echo "Available schemes:"
          xcodebuild -list -project JitStreamer.xcodeproj

          # Clean build directory
          xcodebuild clean -workspace JitStreamer.xcworkspace -scheme JitStreamer || xcodebuild clean -project JitStreamer.xcodeproj -scheme JitStreamer

          # Archive the project
          xcodebuild archive \
            -workspace JitStreamer.xcworkspace \
            -scheme JitStreamer \
            -archivePath build/JitStreamer.xcarchive \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO || \
          xcodebuild archive \
            -project JitStreamer.xcodeproj \
            -scheme JitStreamer \
            -archivePath build/JitStreamer.xcarchive \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Create IPA from archive
          mkdir -p build/Payload
          cp -r build/JitStreamer.xcarchive/Products/Applications/JitStreamer.app build/Payload/
          cd build && zip -r JitStreamer.ipa Payload
          cd ..

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned
          path: build/JitStreamer.ipa
          retention-days: 90 
