name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' JitStreamer.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' JitStreamer.xcodeproj/project.pbxproj

      - name: Archive Build (Unsigned)
        run: |
          xcodebuild clean archive \
            -project JitStreamer.xcodeproj \
            -scheme "JitStreamer" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/JitStreamer.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            ONLY_ACTIVE_ARCH=NO \
            ARCHS="arm64" \
            VALID_ARCHS="arm64" \
            SUPPORTED_PLATFORMS="iphoneos" \
            IPHONEOS_DEPLOYMENT_TARGET=17.0 \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

      - name: Create IPA from Archive
        run: |
          # Copy the .app from the archive
          cp -R build/JitStreamer.xcarchive/Products/Applications/JitStreamer.app .

          # Strip debug symbols
          strip -S -x JitStreamer.app/JitStreamer || true

          # Package into IPA
          mkdir -p Payload
          cp -R JitStreamer.app Payload/
          zip -r JitStreamer.ipa Payload
          rm -rf Payload JitStreamer.app

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer.ipa
          path: JitStreamer.ipa
          retention-days: 90 
