name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create IPA Structure
        run: |
          # Create Payload directory
          mkdir -p Payload/JitStreamer.app
          
          # Copy all app contents
          cp -r JitStreamer/* Payload/JitStreamer.app/
          
          # Create Info.plist if not exists
          if [ ! -f "Payload/JitStreamer.app/Info.plist" ]; then
            cat > Payload/JitStreamer.app/Info.plist << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.stik.jitstreamer</string>
    <key>CFBundleName</key>
    <string>JitStreamer</string>
    <key>CFBundleExecutable</key>
    <string>JitStreamer</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>MinimumOSVersion</key>
    <string>17.4</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
</dict>
</plist>
EOF
          fi
          
          # Create IPA
          zip -r JitStreamer.ipa Payload
          
          # Show contents and size for verification
          echo "IPA Contents:"
          unzip -l JitStreamer.ipa
          echo "IPA Size:"
          ls -lh JitStreamer.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned
          path: JitStreamer.ipa
          retention-days: 90 
