name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
          
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
          
      - name: Build Archive
        run: |
          if [ -f default ]; then scheme=$(cat default); fi
          if [ -d "JitStreamer.xcodeproj" ]; then
            xcodebuild clean archive -project JitStreamer.xcodeproj -scheme "$scheme" -configuration Release -archivePath build/JitStreamer.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          elif [ -d "JitStreamer.xcworkspace" ]; then
            xcodebuild clean archive -workspace JitStreamer.xcworkspace -scheme "$scheme" -configuration Release -archivePath build/JitStreamer.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          else
            echo "No Xcode project or workspace found"
            exit 1
          fi
          
      - name: Create Unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/JitStreamer.xcarchive/Products/Applications/*.app Payload/
          zip -r JitStreamer-unsigned.ipa Payload
          rm -rf Payload
          
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned-ipa
          path: JitStreamer-unsigned.ipa
          retention-days: 7 