name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' JitStreamer.xcodeproj/project.pbxproj

      - name: Build App
        run: |
          xcodebuild clean build \
            -project JitStreamer.xcodeproj \
            -scheme JitStreamer \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA Structure
        run: |
          # Create Payload directory
          mkdir -p Payload
          
          # Copy the built .app
          cp -r build/Build/Products/Release-iphoneos/JitStreamer.app Payload/
          
          # Update Info.plist with required keys
          /usr/libexec/PlistBuddy -c "Add :UIRequiredDeviceCapabilities array" Payload/JitStreamer.app/Info.plist
          /usr/libexec/PlistBuddy -c "Add :UIRequiredDeviceCapabilities:0 string 'arm64'" Payload/JitStreamer.app/Info.plist
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations array" Payload/JitStreamer.app/Info.plist
          /usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations:0 string 'UIInterfaceOrientationPortrait'" Payload/JitStreamer.app/Info.plist
          
          # Create IPA
          zip -r JitStreamer.ipa Payload
          rm -rf Payload build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned
          path: JitStreamer.ipa
          retention-days: 90 
