name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Fix Project Format
        run: |
          # Fix objectVersion
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' JitStreamer.xcodeproj/project.pbxproj
          
          # Fix PBXFileSystemSynchronizedRootGroup to PBXGroup
          sed -i '' 's/PBXFileSystemSynchronizedRootGroup/PBXGroup/g' JitStreamer.xcodeproj/project.pbxproj
          
          # Fix any missing isa keys
          sed -i '' 's/isa = ;/isa = PBXBuildFile;/g' JitStreamer.xcodeproj/project.pbxproj
          
          # Ensure proper project structure
          plutil -convert xml1 JitStreamer.xcodeproj/project.pbxproj

      - name: Build App
        run: |
          # List available schemes
          xcodebuild -list -project JitStreamer.xcodeproj
          
          # Build the app
          xcodebuild clean archive \
            -project JitStreamer.xcodeproj \
            -scheme "JitStreamer" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/JitStreamer.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=NO \
            DEVELOPMENT_TEAM="" \
            IPHONEOS_DEPLOYMENT_TARGET=17.4

      - name: Create IPA Structure
        run: |
          # Create Payload directory
          mkdir -p Payload
          
          # Copy the built .app
          cp -r build/JitStreamer.xcarchive/Products/Applications/JitStreamer.app Payload/
          
          # Create IPA
          zip -r JitStreamer.ipa Payload
          rm -rf Payload build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer-unsigned
          path: JitStreamer.ipa
          retention-days: 90 
