name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' JitStreamer.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' JitStreamer.xcodeproj/project.pbxproj

      - name: Archive Build (Unsigned)
        run: |
          xcodebuild clean archive \
            -project JitStreamer.xcodeproj \
            -scheme "JitStreamer" \
            -configuration Release \
            -archivePath build/JitStreamer.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            IPHONEOS_DEPLOYMENT_TARGET=16.0

      - name: Create IPA from Archive
        run: |
          # Copy the .app from the archive
          cp -R build/JitStreamer.xcarchive/Products/Applications/StikEMU.app .

          # Optionally strip debug symbols from the executable (adjust path if needed)
          strip -S -x JitStreamer.app/StikEMU || true

          # Optionally remove unwanted simulator slices (example shown for x86_64)
          APP_PATH="JitStreamer.app"
          if [ -f "$APP_PATH/JitStreamer" ]; then
            lipo "$APP_PATH/JitStreamer" -info
            lipo -remove x86_64 "$APP_PATH/JitStreamer" -o "$APP_PATH/JitStreamer" || true
          fi

          # Package the app into an IPA
          mkdir -p Payload
          cp -R JitStreamer.app Payload/
          zip -r JitStreamer.ipa Payload
          rm -rf Payload JitStreamer.app

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: JitStreamer.ipa
          path: JitStreamer.ipa
          retention-days: 90
